# Generated by Django 2.2.3 on 2020-09-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='img',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
